import { drizzle } from 'drizzle-orm/expo-sqlite';
import { openDatabaseSync } from 'expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import * as schema from './schema';

const expo = openDatabaseSync('stremiox.db', { enableChangeListener: true });
export const db = drizzle(expo, { schema });

export async function initDB(): Promise<void> {
  // Dynamically import migrations (generated by drizzle-kit)
  const migrations = require('./migrations/migrations');
  await migrate(db, migrations);
} 
